# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04

pool:
  vmImage: 'Ubuntu 16.04'

container: wpilib2020

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build publishToMavenLocal PatchExamples'
    options: '--stacktrace -PlocalPublish'

- script: |
    cd examples/cpp
    chmod +x ./gradlew
    ./gradlew build
  displayName: 'Test Cpp Build'

- script: |
    cd examples/java
    chmod +x ./gradlew
    ./gradlew build
  displayName: 'Test Java Build'

- script: |
    cd examples/kotlin
    chmod +x ./gradlew
    ./gradlew build
  displayName: 'Test Kotlin Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'build/distributions'
    contents: '*'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'Examples'
